### ISSUE TITLE
Program throws SIGSEGV when decoding certain files

### ISSUE THREAD

**Issue by nm17** [drichardson/huffman#2]
Here they are:
[output.tar.gz](https://github.com/drichardson/huffman/files/1444322/output.tar.gz)

**Comment by drichardson** [comment]
Thanks for the report. I can reproduce the crash. I'll take a look.

**Comment by drichardson** [comment]
Did you use a fuzzer to generate the bad input or just do it by hand? If the former, what tool did you use?

**Comment by drichardson** [comment]
Fixed in 818601809f82abc0d916facae3a0e1c9078b21d8.

**Comment by nm17** [comment]
@drichardson it's called american fuzzy lop
