### ISSUE TITLE
Program hangs when decoding certian files.

### ISSUE THREAD

**Issue by nm17** [drichardson/huffman#3]
[output.zip](https://github.com/drichardson/huffman/files/1445383/output.zip)
`id:000000`, `id:000004` creates a 4.2 GB large file even though its only 44 bytes!

**Comment by drichardson** [comment]
In this case, the program is working correctly. The code table defines a symbol that occurs 4211081217 times.

**Comment by drichardson** [comment]
from gdb:

```
Breakpoint 1, read_code_table (in=0x605010, rootOut=0x7fffffffe918, dataBytesOut=0x7fffffffe910)
(gdb) p dataBytes
$5 = 4211081217


```
