### ISSUE TITLE
Memory leaking?

### ISSUE THREAD

**Issue by ghost** [drichardson/huffman#5]
for(i = 1; i < n; ++i)
	{
		/* Set m1 and m2 to the two subsets of least probability. */
		m1 = pSF[0];
		m2 = pSF[1];

		/* Replace m1 and m2 with a set {m1, m2} whose probability
		 * is the sum of that of m1 and m2. */
		pSF[0] = m1->parent = m2->parent =
			new_nonleaf_node(m1->count + m2->count, m1, m2);
//Fix         free(pSF[1]);
		pSF[1] = NULL;//In the original file this is not freed.
		
		/* Put newSet into the correct count position in pSF. */
		qsort(pSF, n, sizeof(pSF[0]), SFComp);
	}

**Comment by drichardson** [comment]
No it's not leaking.

Here's the definition of [new_nonleaf_node](https://github.com/drichardson/huffman/blob/78e19b28974e55865b9ae0156227ab36b1aaed95/huffman.c#L157):

```c
static huffman_node*
new_nonleaf_node(unsigned long count, huffman_node *zero, huffman_node *one)
{
	huffman_node *p = (huffman_node*)malloc(sizeof(huffman_node));
	p->isLeaf = 0;
	p->count = count;
	p->zero = zero;
	p->one = one;
	p->parent = 0;
	
	return p;
}
```
There you can see that those pointers are still attached to the tree, and are not leaked. They are freed in `free_huffman_tree`.

**Comment by drichardson** [comment]
BTW, just to make sure there weren't any leaks I just ran it through valgrind and it looks fine.

```bash
huffman (master)$ valgrind --leak-check=full --show-leak-kinds=all ./huffcode -i test_data/3_line -o 3_line.comp
==20607== Memcheck, a memory error detector
==20607== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20607== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==20607== Command: ./huffcode -i test_data/3_line -o 3_line.comp
==20607==
==20607== error calling PR_SET_PTRACER, vgdb might block
==20607==
==20607== HEAP SUMMARY:
==20607==     in use at exit: 1,104 bytes in 2 blocks
==20607==   total heap usage: 50 allocs, 48 frees, 7,066 bytes allocated
==20607==
==20607== 552 bytes in 1 blocks are still reachable in loss record 1 of 2
==20607==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==20607==    by 0x48C20FA: __fopen_internal (iofopen.c:65)
==20607==    by 0x1093E5: main (huffcode.c:91)
==20607==
==20607== 552 bytes in 1 blocks are still reachable in loss record 2 of 2
==20607==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==20607==    by 0x48C20FA: __fopen_internal (iofopen.c:65)
==20607==    by 0x109444: main (huffcode.c:104)
==20607==
==20607== LEAK SUMMARY:
==20607==    definitely lost: 0 bytes in 0 blocks
==20607==    indirectly lost: 0 bytes in 0 blocks
==20607==      possibly lost: 0 bytes in 0 blocks
==20607==    still reachable: 1,104 bytes in 2 blocks
==20607==         suppressed: 0 bytes in 0 blocks
==20607==
==20607== For counts of detected and suppressed errors, rerun with: -v
==20607== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

The *still reachable* blocks are the 2 `FILE*` that are not closed before program exit. Since they are in the `main` function that exits immediately after compressing/decompressing, it isn't a problem since the underlying file descriptors will be closed by the operating system. Though if you wanted to make valgrind report no errors here, we could add a patch to close the files.

**Comment by ghost** [comment]
Sorry, I am stupid, I even "fix it" in the local file. I see your point, you are right. Thanks for your explanation. :D

**Comment by drichardson** [comment]
No worries. I ended up "fixing" the FILE* issue I mentioned, just so valgrind wouldn't complain.

83f9a9221bdd64a04fcbd95a8488a224bdc63ab2
