### ISSUE TITLE
not super important, but a CMakeLists shoud always start with `cmake_minimum_required` then `project`, and nothing between these 2 commands.

### ISSUE THREAD

**Issue by drichardson** [drichardson/huffman#8]
not super important, but a CMakeLists shoud always start with `cmake_minimum_required` then `project`, and nothing between these 2 commands.

_Originally posted by @SpaceIm in https://github.com/conan-io/conan-center-index/pull/5247#discussion_r615975469_

**Comment by SpaceIm** [comment]
Actually I was wrong, `CMAKE_OSX_DEPLOYMENT_TARGET` is an exception: https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by drichardson** [comment]
> 
> 
> Actually I was wrong, `CMAKE_OSX_DEPLOYMENT_TARGET` is an exception: https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

Fixed in 102150ac8ca5d5b8aa4a9ddd897a98e6793b8342
